# Follows pattern
# base_data_path: <base path on system; common folder in which ephy_testing_data + ophys_testing_data are found>
#
# pipelines:
#   pipeline_name:
#     DataInterfaceName:
#       file_or_folder_path: <relative path>
#       other_source_data_inputs: <insert if needed>
#     AdditionalDataInterface: ...

pipelines:

  SpikeGLX-Phy:
    SpikeGLXRecordingInterface:
      file_path: ephy_testing_data/spikeglx/Noise4Sam_g0/Noise4Sam_g0_imec0/Noise4Sam_g0_t0.imec0.ap.bin
    PhySortingInterface:
      folder_path: ephy_testing_data/phy/phy_example_0

  SpikeGLX-v1-SingleProbe-AP:
    SpikeGLXDataInterface:
      file_path: ephy_testing_data/spikeglx/Noise4Sam_g0/Noise4Sam_g0_imec0/Noise4Sam_g0_t0.imec0.ap.bin