# Follows pattern
# pipelines:
#   pipeline_name:
#     DataInterfaceName:
#       file_or_folder_path: <relative path>
#       other_source_data_inputs: <insert if needed>
#     AdditionalDataInterface: ...

pipelines:

  SpikeGLX-Phy:
    SpikeGLXRecordingInterface:
      file_path: ephy_testing_data/spikeglx/Noise4Sam_g0/Noise4Sam_g0_imec0/Noise4Sam_g0_t0.imec0.ap.bin
    PhySortingInterface:
      folder_path: ephy_testing_data/phy/phy_example_0


  SpikeGLX_v1_SingleProbe_AP:
    SpikeGLXRecordingInterface:
      file_path: ephy_testing_data/spikeglx/Noise4Sam_g0/Noise4Sam_g0_imec0/Noise4Sam_g0_t0.imec0.ap.bin


  SpikeGLXConverter-Phy:
    SpikeGLXConverter:
      file_path: ephy_testing_data/spikeglx/Noise4Sam_g0
    PhySortingInterface:
      folder_path: ephy_testing_data/phy/phy_example_0


  Suite2P_SinglePlane_SingleChannel:
    Suite2pSegmentationInterface:
      folder_path: ophys_testing_data/segmentation_datasets/suite2p

  Caiman_SinglePlane_SingleChannel:
    CaimanSegmentationInterface:
      file_path: ophys_testing_data/segmentation_datasets/caiman/caiman_analysis.hdf5

  ScanImage_SinglePlane_SingleChannel:
    ScanImageImagingInterface:
      file_path: ophys_testing_data/imaging_datasets/ScanImage/scanimage_20220801_single.tif

  TDT:
    TdtRecordingInterface:
      folder_path: ephy_testing_data/tdt/aep_05

  CellExplorer:
    CellExplorerRecordingInterface:
      folder_path: ephy_testing_data/cellexplorer/dataset_4/Peter_MS22_180629_110319_concat_stubbed

  CellExplorerUnits:
    CellExplorerRecordingInterface:
      folder_path: ephy_testing_data/cellexplorer/dataset_4/Peter_MS22_180629_110319_concat_stubbed
    CellExplorerSortingInterface:
      file_path: ephy_testing_data/cellexplorer/dataset_4/Peter_MS22_180629_110319_concat_stubbed/Peter_MS22_180629_110319_concat_stubbed.spikes.cellinfo.mat

  IntanSingleFileRecording:
    IntanRecordingInterface:
      file_path: ephy_testing_data/intan/intan_rhd_test_1.rhd

  BrukerTiffMultiChannelSinglePlane:
    BrukerTiffSinglePlaneConverter:
      folder_path: ophys_testing_data/imaging_datasets/BrukerTif/NCCR32_2023_02_20_Into_the_void_t_series_baseline-000

  DeepLabCut:
    DeepLabCutInterface:
      file_path: behavior_testing_data/DLC/m3v1mp4DLC_resnet50_openfieldAug20shuffle1_30000.h5
      config_file_path: behavior_testing_data/DLC/config.yaml
