# Follows pattern
# pipelines:
#   pipeline_name:
#     test: Optional[bool]
#     metadata:
#       key:
#         name: value
#         array:
#           - First value
#           - Second value
#     interfaces:
#       DataInterfaceName:
#         file_or_folder_path: <relative path>
#         other_source_data_inputs: <insert if needed>
#       AdditionalDataInterface: ...

# NOTE: Can also just provide interfaces directly below pipeline name

pipelines:

  SpikeGLX-Phy:
    SpikeGLXRecordingInterface:
      file_path: ephy_testing_data/spikeglx/Noise4Sam_g0/Noise4Sam_g0_imec0/Noise4Sam_g0_t0.imec0.ap.bin
    PhySortingInterface:
      folder_path: ephy_testing_data/phy/phy_example_0

  SpikeGLX_v1_SingleProbe_AP:
    SpikeGLXRecordingInterface:
      file_path: ephy_testing_data/spikeglx/Noise4Sam_g0/Noise4Sam_g0_imec0/Noise4Sam_g0_t0.imec0.ap.bin

  Suite2P_SinglePlane_SingleChannel:
    test: false
    metadata:
      NWBFile:
        session_start_time: 2024-05-09T00:00
      Ophys:
        ImagingPlane:
          -
            excitation_lambda: NaN
            optical_channel:
              -
                emission_lambda: NaN

    interfaces:
      Suite2pSegmentationInterface:
        folder_path: ophys_testing_data/segmentation_datasets/suite2p

  Caiman_SinglePlane_SingleChannel:
    test: false
    metadata:
      NWBFile:
        session_start_time: 2024-05-09T00:00
      Ophys:
        ImagingPlane:
          -
            excitation_lambda: NaN
            optical_channel:
              -
                emission_lambda: NaN

    interfaces:
      CaimanSegmentationInterface:
        file_path: ophys_testing_data/segmentation_datasets/caiman/caiman_analysis.hdf5

  ScanImage_SinglePlane_SingleChannel:

    metadata:
      Ophys:
        ImagingPlane:
          - 
            excitation_lambda: NaN
            optical_channel:
              -
                emission_lambda: NaN

    interfaces:
      ScanImageImagingInterface:
        file_path: ophys_testing_data/imaging_datasets/ScanImage/sample_scanimage_version_3_8.tiff

  TDT:
    metadata:
        NWBFile:
          session_start_time: 2024-05-09T00:00

    interfaces:
      TdtRecordingInterface:
        folder_path: ephy_testing_data/tdt/aep_05
        gain: 1


  CellExplorer:
    metadata:
      NWBFile:
        session_start_time: 2024-05-09T00:00

    interfaces:
      CellExplorerRecordingInterface:
        folder_path: ephy_testing_data/cellexplorer/dataset_4/Peter_MS22_180629_110319_concat_stubbed

  CellExplorerUnits:
    metadata:
      NWBFile:
        session_start_time: 2024-05-09T00:00

    interfaces:
      CellExplorerRecordingInterface:
        folder_path: ephy_testing_data/cellexplorer/dataset_4/Peter_MS22_180629_110319_concat_stubbed
      CellExplorerSortingInterface:
        file_path: ephy_testing_data/cellexplorer/dataset_4/Peter_MS22_180629_110319_concat_stubbed/Peter_MS22_180629_110319_concat_stubbed.spikes.cellinfo.mat

  CellExplorerSortingOnly:
    metadata:
      NWBFile:
        session_start_time: 2024-05-09T00:00

    interfaces:
      CellExplorerSortingInterface:
        file_path: ephy_testing_data/cellexplorer/dataset_4/Peter_MS22_180629_110319_concat_stubbed/Peter_MS22_180629_110319_concat_stubbed.spikes.cellinfo.mat

  IntanSingleFileRecording:
    metadata:
      NWBFile:
        session_start_time: 2024-05-09T00:00
      Ecephys:
        ElectrodeGroup:
          -
            location: Test location
          -
            location: Test location
          -
            location: Test location



    interfaces:
      IntanRecordingInterface:
        file_path: ephy_testing_data/intan/intan_rhd_test_1.rhd

  BrukerTiffMultiChannelSinglePlane:
    metadata:
      Ophys:
        ImagingPlane:
          -
            excitation_lambda: NaN
            optical_channel:
              -
                emission_lambda: NaN

    interfaces:
      BrukerTiffSinglePlaneConverter:
        folder_path: ophys_testing_data/imaging_datasets/BrukerTif/NCCR32_2023_02_20_Into_the_void_t_series_baseline-000

  DeepLabCut:
    metadata:
      NWBFile:
        session_start_time: 2024-05-09T00:00

    interfaces:
      DeepLabCutInterface:
        file_path: behavior_testing_data/DLC/m3v1mp4DLC_resnet50_openfieldAug20shuffle1_30000.h5
        config_file_path: behavior_testing_data/DLC/config.yaml
