name: nwb-guide
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.9.18
  - PyInstaller = 6.3.0
  - nodejs = 18.16.1
  - numcodecs = 0.11.0
  - lxml = 4.9.3  # pypi build fails due to x64/arm64 mismatch so install from conda-forge
  - pyedflib = 0.1.32  # pypi build fails due to x64/arm64 mismatch so install from conda-forge
  - numpy  # may have x64/arm64 mismatch issues so install from conda-forge
  - pytables = 3.8 # pypi build fails on arm64 so install from conda-forge (used by neuroconv deps)
  # install these from conda-forge so that dependent packages get included in the distributable
  - jsonschema = 4.18.0  # installs jsonschema-specifications
  - pydantic[email] = 1.10.12  # installs email-validator
  - pip
  - pip:
      - chardet == 5.1.0
      - configparser == 6.0.0
      - flask == 2.3.2
      - flask-cors == 4.0.0
      - flask_restx == 1.1.0
      - neuroconv @ git+https://github.com/catalystneuro/neuroconv.git@main#neuroconv[full]
      - dandi >= 0.60.0
      - pytest == 7.4.0
      - pytest-cov == 4.1.0
      - scikit-learn == 1.4.0
