blank_issues_enabled: true
contact_links:
  - name: Request Format Support
    url: https://github.com/catalystneuro/neuroconv/issues/new?assignees=&labels=enhancement%2Cdata+interfaces&projects=&template=format_request.yml&title=%5BNew+Format%5D%3A+
    about: Request support for a new format on NeuroConv.
  - name: NWB Community and Contact
    url: https://www.nwb.org/contact-us/
    about: Have a bunch of really specific questions? Just looking to learn more about NWB? Connect with the greater NWB community!
  - name: NWB Best Practices
    url: https://nwbinspector.readthedocs.io/en/dev/best_practices/best_practices_index.html
    about: Check out the full list of Best Practices for making NWBFiles.
