name: Feature Request
description: Suggest an idea for a brand new feature for the NWB GUIDE, or a change to an existing one.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your suggestion!

        We welcome any ideas about how to make the **NWB GUIDE** better for the community.

        Please keep in mind that new features may not get implemented immediately.
  - type: textarea
    id: summary
    attributes:
      label: What would you like to see added to the NWB GUIDE?
      description: |
        What are you trying to achieve with **NWB GUIDE**?

        Is this a more convenient way to do something that is already possible, or is a workaround currently unfeasible?
    validations:
      required: true
  - type: dropdown
    id: interest
    attributes:
      label: Do you have any interest in helping implement the feature?
      description: |
        We appreciate any help you can offer!

        For information on how to contribute, please refer to our [developer guide](https://nwb-guide.readthedocs.io/en/latest/developer_guide.html).
      options:
        - Yes.
        - Yes, but I would need guidance.
        - No.
    validations:
      required: true


  - type: dropdown
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: Do you agree to follow our [Code of Conduct](https://github.com/catalystneuro/tqdm_publisher/blob/main/.github/CODE_OF_CONDUCT.md)?
      options:
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: existing_issues
    attributes:
      label: Did you confirm this feature was not already reported?
      description: This feature should not already be [reported](https://github.com/NeurodataWithoutBorders/nwb-guide/issues) in an existing issue
      options:
        - "Yes"
    validations:
      required: true
