name: Windows Release
run-name: ${{ github.actor }} is building a Windows release for NWB GUIDE

on:
  workflow_dispatch:

jobs:
  deploy-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: nwb-guide
          conda-remove-defaults: true

      - name: Create and activate environment
        run: conda env update --name nwb-guide --file environments/environment-Windows.yml

      - uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install package.json modules and their dependencies
        run: npm install --verbose

      - name: Build and deploy on Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy:win
