name: Windows Release
run-name: ${{ github.actor }} is building a Windows release for NWB GUIDE

on:
  workflow_dispatch:

jobs:
  deploy-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nwb-guide
          environment-file: environments/environment-Windows.yml
          auto-activate-base: false

      - name: Install package.json modules and their dependencies
        run: npm install --verbose

      - name: Build and deploy on Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy:win
