name: Windows Release
run-name: ${{ github.actor }} is building a Windows release for NWB GUIDE

on:
  workflow_dispatch:

jobs:
  deploy-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync --locked

      - name: Add the virtual environment to PATH
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "$GITHUB_WORKSPACE\\.venv\\Scripts" >> "$GITHUB_PATH"
          else
            echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
          fi
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> "$GITHUB_ENV"

      - uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install package.json modules and their dependencies
        run: npm install --verbose

      - name: Build and deploy on Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy:win
