name: Daily Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *" # Daily at 10am EST

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  DevTests:
    uses: ./.github/workflows/testing_dev.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  LiveServices:
    uses: ./.github/workflows/testing_dev_with_live_services.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DANDI_STAGING_API_KEY: ${{ secrets.DANDI_STAGING_API_KEY }}

  BuildTests:
    uses: ./.github/workflows/testing_flask_build_and_dist.yml

  ExampleDataCache:
    uses: ./.github/workflows/example_data_cache.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_GIN_BUCKET: ${{ secrets.S3_GIN_BUCKET }}

  ExampleDataTests:
    needs: ExampleDataCache
    uses: ./.github/workflows/testing_pipelines.yml
