name: Deploy

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # NOTE: diagnostic branch only. Trimmed to just the flaky E2E job to iterate quickly. Do not merge.
  E2ELiveServices:
    uses: ./.github/workflows/testing_dev_e2e_with_live_services.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DANDI_SANDBOX_API_KEY: ${{ secrets.DANDI_SANDBOX_API_KEY }}
