name: E2E Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  DevTests:
    uses: ./.github/workflows/testing_dev.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  LiveServices:
    uses: ./.github/workflows/testing_dev_with_live_services.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DANDI_STAGING_API_KEY: ${{ secrets.DANDI_STAGING_API_KEY }}
