name: Example data pipeline tests
on:
  workflow_call:

jobs:

  run:
    # Will read on PR dashboard as 'Deploy / ExampleDataTests / {os}'
    # Action dashboard identified by 'Example data pipeline tests'
    # Requirement settings identified as 'ExampleDataTests / {os}'
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
# Fails randomly on daily tests
#          - os: ubuntu-latest

          - os: macos-latest  # Mac arm64 runner

          - os: macos-15-intel  # Mac x64 runner

          - os: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync --locked

      - name: Add the virtual environment to PATH
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "$GITHUB_WORKSPACE\\.venv\\Scripts" >> "$GITHUB_PATH"
          else
            echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
          fi
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> "$GITHUB_ENV"

      - name: Use Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install GUIDE
        run: npm ci --verbose

      - name: Manually remove matplotlib
        run: uv pip uninstall matplotlib

      # Load example data caches
      - name: Get ephy_testing_data current head hash
        id: ephys
        run: |
          HASH=$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)
          if [ -z "$HASH" ]; then echo "Failed to fetch ephy_testing_data hash" && exit 1; fi
          echo "HASH_EPHY_DATASET=$HASH" >> $GITHUB_OUTPUT

      - name: Cache ephys dataset - ${{ steps.ephys.outputs.HASH_EPHY_DATASET }}
        uses: actions/cache@v5
        id: cache-ephys-datasets
        with:
          path: ./ephy_testing_data
          key: ephys-datasets-v2-${{ matrix.os }}-${{ steps.ephys.outputs.HASH_EPHY_DATASET }}

      - name: Get ophys_testing_data current head hash
        id: ophys
        run: |
          HASH=$(git ls-remote https://gin.g-node.org/CatalystNeuro/ophys_testing_data.git HEAD | cut -f1)
          if [ -z "$HASH" ]; then echo "Failed to fetch ophys_testing_data hash" && exit 1; fi
          echo "HASH_OPHYS_DATASET=$HASH" >> $GITHUB_OUTPUT

      - name: Cache ophys dataset - ${{ steps.ophys.outputs.HASH_OPHYS_DATASET }}
        uses: actions/cache@v5
        id: cache-ophys-datasets
        with:
          path: ./ophys_testing_data
          key: ophys-datasets-${{ matrix.os }}-${{ steps.ophys.outputs.HASH_OPHYS_DATASET }}

      - name: Get behavior_testing_data current head hash
        id: behavior
        run: |
          HASH=$(git ls-remote https://gin.g-node.org/CatalystNeuro/behavior_testing_data.git HEAD | cut -f1)
          if [ -z "$HASH" ]; then echo "Failed to fetch behavior_testing_data hash" && exit 1; fi
          echo "HASH_BEHAVIOR_DATASET=$HASH" >> $GITHUB_OUTPUT

      - name: Cache behavior dataset - ${{ steps.behavior.outputs.HASH_BEHAVIOR_DATASET }}
        uses: actions/cache@v5
        id: cache-behavior-datasets
        with:
          path: ./behavior_testing_data
          key: behavior-datasets-${{ matrix.os }}-${{ steps.behavior.outputs.HASH_BEHAVIOR_DATASET }}

      # Run pipeline tests
      - if: matrix.os != 'ubuntu-latest'
        name: Run tests
        run: npm run test:pipelines
        env:
          GIN_DATA_DIRECTORY: ${{ github.workspace }}

      - if: matrix.os == 'ubuntu-latest'
        name: Run tests with xvfb
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:pipelines
        env:
          GIN_DATA_DIRECTORY: ${{ github.workspace }}

      - name: Archive Pipeline Test Screenshots
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-pipelines-screenshots-${{ matrix.os }}
          path: docs/assets/tutorials/test-pipelines
          retention-days: 1
          overwrite: true
