name: Back-end Tests
on:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST
  pull_request:

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 1  # increase to reset cache manually

jobs:
  testing:
    name: Back-end tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python-version: "3.9"
            os: ubuntu-latest
            label: tools/anaconda-env/environment-Linux.yml
            prefix: /usr/share/miniconda3/envs/env-electron-python

          - python-version: "3.10"
            os: macos-latest
            label: tools/anaconda-env/environment-Mac.yml
            prefix: /Users/runner/miniconda3/envs/env-electron-python

          - python-version: "3.9"
            os: windows-latest
            label: tools/anaconda-env/environment-Windows.yml
            prefix: C:\Miniconda3\envs\env-electron-python


    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags

      # see https://github.com/conda-incubator/setup-miniconda#caching-environments
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: env-electron-python
          use-mamba: true

      - name: Set cache date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v2
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}-${{ runner.arch }}-${{steps.get-date.outputs.today }}-${{ hashFiles(matrix.label) }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if environment file has not changed
          CACHE_NUMBER: 0
        id: cache

      # - uses: actions/cache@v2
      #   with:
      #     path: ${{ matrix.prefix }}
      #     key: ${{ matrix.os }}-conda-${{ hashFiles(matrix.label) }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      #   id: cache

      - name: Update environment
        run:
          mamba env update -n env-electron-python -f ${{ matrix.label }}
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install GUIDE
        run: npm ci

      - name: Run tests
        run: npm run test
