name: Minimal and Full Tests
on:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST
  pull_request:

jobs:
  testing:
    name: Minimal and full tests on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest, macos-latest, windows-latest]  # Add others later
        include:
          - os: ubuntu-latest
            label: tools/anaconda-env/environment-Linux.yml
            prefix: /usr/share/miniconda3/envs/my-env

          - os: macos-latest
            label: tools/anaconda-env/environment-Mac.yml
            prefix: /Users/runner/miniconda3/envs/my-env

          - os: windows-latest
            label: tools/anaconda-env/environment-Windows.yml
            prefix: C:\Miniconda3\envs\my-env


    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-version: latest
            environment-file: ${{ matrix.label }}
            activate-environment: env-electron-python
            python-version: ${{ matrix.python-version }}

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.os }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Run tests
        run: |
          npm ci
          npm run test
