name: Flask build and distributable tests
on:
  workflow_call:

jobs:

  run:
    # Will read on PR dashboard as 'Deploy / BuildTests / {os}'
    # Action dashboard identified by 'Flask build and distributable tests'
    # Requirement settings identified as 'BuildTests / {os}'
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          # No linux in this matrix since installation instructions use dev mode instead of distributable

          - os: macos-latest  # Mac arm64 runner
            label: environments/environment-MAC-apple-silicon.yml

          - os: macos-13  # Mac x64 runner
            label: environments/environment-MAC-intel.yml

          - os: windows-latest
            label: environments/environment-Windows.yml

    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags

      - name: Printout architecture
        run: uname -m

      # see https://github.com/conda-incubator/setup-miniconda#caching-environments
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: nwb-guide
          use-mamba: true

      - name: Set cache date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Mamba env
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}-${{ runner.arch }}-${{steps.get-date.outputs.today }}-${{ hashFiles(matrix.label) }}-${{ env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: ${{ env.CACHE_NUMBER }}
        id: cache

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Update environment
        run: mamba env update -f ${{ matrix.label }}

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install GUIDE
        run: npm ci --verbose

      # Fix for macos build - remove bad sonpy file
      - if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
        run: rm -f "$CONDA_PREFIX/lib/python3.9/site-packages/sonpy/linux/sonpy.so"

      - name: Build PyFlask distribution
        run: npm run build:flask

      - name: Run test on distributed executable
        run: node tests/testPyinstallerExecutable.js

      - name: Run Python tests on distributed executable
        run: npm run test:executable
