name: Update package.lock

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout New Branch
        run: |
          git checkout -b update_package_lock
      - name: Update package.lock file
        run: |
          npm install
      - name: Commit Changes and Create Pull Request
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git commit . -m "Update package.lock file"
          git push origin update_package_lock
          gh pr create --title "[Github.CI] Update package.lock file" --body "Updated package.lock file to match package.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
